[
  ['0', 'None', '', '10-bit Action Codes 0x00', ''],
  ['1', 'None', '', '10-bit Action Codes 0x01', ''],
  ['2', 'None', '', '10-bit Action Codes 0x02', ''],
  ['3', 'None', '', '10-bit Action Codes 0x03', ''],
  ['4', 'None', '', '10-bit Action Codes 0x04', ''],
  ['5', 'None', '', '10-bit Action Codes 0x05', ''],
  ['6', 'None', '', '10-bit Action Codes 0x06', ''],
  ['7', 'None', '', '10-bit Action Codes 0x07', ''],
  ['8', 'None', '', '10-bit Action Codes 0x08', ''],
  ['9', 'None', '', '10-bit Action Codes 0x09', ''],
  ['10', 'None', '', '10-bit Action Codes 0x0A', ''],
  ['11', 'None', '', '10-bit Action Codes 0x0B', ''],
  ['12', 'None', '', '10-bit Action Codes 0x0C', ''],
  ['13', 'None', '', '10-bit Action Codes 0x0D', ''],
  ['14', 'None', '', '10-bit Action Codes 0x0E', ''],
  ['15', 'None', '', '10-bit Action Codes 0x0F', ''],
  ['16', 'None', '', '10-bit Action Codes 0x10', ''],
  ['17', 'None', '', '10-bit Action Codes 0x11', ''],
  ['18', 'None', '', '10-bit Action Codes 0x12', ''],
  ['19', 'None', '', '10-bit Action Codes 0x13', ''],
  ['20', 'None', '', '10-bit Action Codes 0x14', ''],
  ['21', 'None', '', '10-bit Action Codes 0x15', ''],
  ['22', 'None', '', '10-bit Action Codes 0x16', ''],
  ['23', 'None', '', '10-bit Action Codes 0x17', ''],
  ['24', 'None', '', '10-bit Action Codes 0x18', ''],
  ['25', 'None', '', '10-bit Action Codes 0x19', ''],
  ['26', 'None', '', '10-bit Action Codes 0x1A', ''],
  ['27', 'None', '', '10-bit Action Codes 0x1B', ''],
  ['28', 'None', '', '10-bit Action Codes 0x1C', ''],
  ['29', 'None', '', '10-bit Action Codes 0x1D', ''],
  ['30', 'None', '', '10-bit Action Codes 0x1E', ''],
  ['31', 'None', '', '10-bit Action Codes 0x1F', ''],
  [
    '32',
    'ASCII',
    'SPACE',
    'Space',
    'While SPACE is used for keymaps and chord, just a " " is used in chord outputs. This action is unique in this way. Technically it is \'printable\', but it is not visible.',
  ],
  ['33', 'ASCII', '!', 'Exclamation Point', ''],
  ['34', 'ASCII', '"', 'Double Quote', ''],
  ['35', 'ASCII', '#', 'Hash Symbol', ''],
  ['36', 'ASCII', '$', 'Dollar Sign', ''],
  ['37', 'ASCII', '%', 'Percent', ''],
  ['38', 'ASCII', '&', 'Amperstand', ''],
  ['39', 'ASCII', "'", 'Single Quote', ''],
  ['40', 'ASCII', '(', 'Left Parenthesis', ''],
  ['41', 'ASCII', ')', 'Right Parenthesis', ''],
  ['42', 'ASCII', '*', 'Asterisk', ''],
  ['43', 'ASCII', '+', 'Plus', ''],
  ['44', 'ASCII', ',', 'Comma', ''],
  ['45', 'ASCII', '-', 'Minus', ''],
  ['46', 'ASCII', '.', 'Period', ''],
  ['47', 'ASCII', '/', 'Forward Slash', ''],
  ['48', 'ASCII', '0', 'Zero', ''],
  ['49', 'ASCII', '1', 'One', ''],
  ['50', 'ASCII', '2', 'Two', ''],
  ['51', 'ASCII', '3', 'Three', ''],
  ['52', 'ASCII', '4', 'Four', ''],
  ['53', 'ASCII', '5', 'Five', ''],
  ['54', 'ASCII', '6', 'Six', ''],
  ['55', 'ASCII', '7', 'Seven', ''],
  ['56', 'ASCII', '8', 'Eight', ''],
  ['57', 'ASCII', '9', 'Nine', ''],
  ['58', 'ASCII', ':', 'Colon', ''],
  ['59', 'ASCII', ';', 'Semicolon', ''],
  ['60', 'ASCII', '<', 'Less Than', ''],
  ['61', 'ASCII', '=', 'Equals', ''],
  ['62', 'ASCII', '>', 'Greater Than', ''],
  ['63', 'ASCII', '?', 'Question Mark', ''],
  ['64', 'ASCII', '@', 'At Symbol', ''],
  ['65', 'ASCII', 'A', 'Uppercase A', ''],
  ['66', 'ASCII', 'B', 'Uppercase B', ''],
  ['67', 'ASCII', 'C', 'Uppercase C', ''],
  ['68', 'ASCII', 'D', 'Uppercase D', ''],
  ['69', 'ASCII', 'E', 'Uppercase E', ''],
  ['70', 'ASCII', 'F', 'Uppercase F', ''],
  ['71', 'ASCII', 'G', 'Uppercase G', ''],
  ['72', 'ASCII', 'H', 'Uppercase H', ''],
  ['73', 'ASCII', 'I', 'Uppercase I', ''],
  ['74', 'ASCII', 'J', 'Uppercase J', ''],
  ['75', 'ASCII', 'K', 'Uppercase K', ''],
  ['76', 'ASCII', 'L', 'Uppercase L', ''],
  ['77', 'ASCII', 'M', 'Uppercase M', ''],
  ['78', 'ASCII', 'N', 'Uppercase N', ''],
  ['79', 'ASCII', 'O', 'Uppercase O', ''],
  ['80', 'ASCII', 'P', 'Uppercase P', ''],
  ['81', 'ASCII', 'Q', 'Uppercase Q', ''],
  ['82', 'ASCII', 'R', 'Uppercase R', ''],
  ['83', 'ASCII', 'S', 'Uppercase S', ''],
  ['84', 'ASCII', 'T', 'Uppercase T', ''],
  ['85', 'ASCII', 'U', 'Uppercase U', ''],
  ['86', 'ASCII', 'V', 'Uppercase V', ''],
  ['87', 'ASCII', 'W', 'Uppercase W', ''],
  ['88', 'ASCII', 'X', 'Uppercase X', ''],
  ['89', 'ASCII', 'Y', 'Uppercase Y', ''],
  ['90', 'ASCII', 'Z', 'Uppercase Z', ''],
  ['91', 'ASCII', '[', 'Left Bracket', ''],
  ['92', 'ASCII', '\\', 'Backslash', ''],
  ['93', 'ASCII', ']', 'Right Bracket', ''],
  ['94', 'ASCII', '^', 'Carrot', ''],
  ['95', 'ASCII', '_', 'Underscore', ''],
  ['96', 'ASCII', '`', 'Grave Mark', ''],
  [
    '97',
    'ASCII',
    'a',
    'Lowercase a',
    'Lowercase ASCII letters are needed for the linguistics processing',
  ],
  ['98', 'ASCII', 'b', 'Lowercase b', ''],
  ['99', 'ASCII', 'c', 'Lowercase c', ''],
  ['100', 'ASCII', 'd', 'Lowercase d', ''],
  ['101', 'ASCII', 'e', 'Lowercase e', ''],
  ['102', 'ASCII', 'f', 'Lowercase f', ''],
  ['103', 'ASCII', 'g', 'Lowercase g', ''],
  ['104', 'ASCII', 'h', 'Lowercase h', ''],
  ['105', 'ASCII', 'i', 'Lowercase i', ''],
  ['106', 'ASCII', 'j', 'Lowercase j', ''],
  ['107', 'ASCII', 'k', 'Lowercase k', ''],
  ['108', 'ASCII', 'l', 'Lowercase l', ''],
  ['109', 'ASCII', 'm', 'Lowercase m', ''],
  ['110', 'ASCII', 'n', 'Lowercase n', ''],
  ['111', 'ASCII', 'o', 'Lowercase o', ''],
  ['112', 'ASCII', 'p', 'Lowercase p', ''],
  ['113', 'ASCII', 'q', 'Lowercase q', ''],
  ['114', 'ASCII', 'r', 'Lowercase r', ''],
  ['115', 'ASCII', 's', 'Lowercase s', ''],
  ['116', 'ASCII', 't', 'Lowercase t', ''],
  ['117', 'ASCII', 'u', 'Lowercase u', ''],
  ['118', 'ASCII', 'v', 'Lowercase v', ''],
  ['119', 'ASCII', 'w', 'Lowercase w', ''],
  ['120', 'ASCII', 'x', 'Lowercase x', ''],
  ['121', 'ASCII', 'y', 'Lowercase y', ''],
  ['122', 'ASCII', 'z', 'Lowercase z', ''],
  ['123', 'ASCII', '{', 'Left Curly Brace', ''],
  ['124', 'ASCII', '|', 'Pipe', ''],
  ['125', 'ASCII', '}', 'Right Curly Brace', ''],
  ['126', 'ASCII', '~', 'Tilde', ''],
  ['127', 'ASCII', 'DEL', 'Delete', ''],
  ['128', 'CP-1252', '€', 'Uppercase cedilla', ''],
  ['129', '', '', 'HOP (High Octet Preset)', ''],
  ['130', 'CP-1252', '‚', 'Single Low-9 Quotation Mark', ''],
  ['131', 'CP-1252', 'ƒ', 'Latin Small Letter f with Hook; Florin', ''],
  ['132', 'CP-1252', '„', 'Double Low-9 Quotation Mark', ''],
  ['133', 'CP-1252', '…', 'Horizontal Ellipsis', ''],
  ['134', 'CP-1252', '†', 'Dagger', ''],
  ['135', 'CP-1252', '‡', 'Double Dagger', ''],
  ['136', 'CP-1252', 'ˆ', 'Circumflex', ''],
  ['137', 'CP-1252', '‰', 'Per Mile', ''],
  ['138', 'CP-1252', 'Š', 'Captial S Caron', ''],
  ['139', 'CP-1252', '‹', 'Left Guillemet', ''],
  ['140', 'CP-1252', 'Œ', 'Captial Ligature OE', ''],
  ['141', '', '', 'RI (Reverse Index)', ''],
  ['142', 'CP-1252', 'Ž', 'Captial Z Caron', ''],
  ['143', '', '', 'SS3 (Single-Shift G3)', ''],
  ['144', '', '', 'DCS (Device Control String)', ''],
  ['145', 'CP-1252', '‘', 'Single Quote Left', ''],
  ['146', 'CP-1252', '’', 'Single Quote Right', ''],
  ['147', 'CP-1252', '“', 'Double Quote Left', ''],
  ['148', 'CP-1252', '”', 'Double Quote Right', ''],
  ['149', 'CP-1252', '•', 'Bullet', ''],
  ['150', 'CP-1252', '–', 'En Dash', ''],
  ['151', 'CP-1252', '—', 'Em Dash', ''],
  ['152', 'CP-1252', '˜', 'Small Tilde', ''],
  ['153', 'CP-1252', '™', 'Trademark', ''],
  ['154', 'CP-1252', 'š', 'Small s Carson', ''],
  ['155', 'CP-1252', '›', 'Right Guillement', ''],
  ['156', 'CP-1252', 'œ', 'Small Ligature oe', ''],
  ['157', 'CP-1252', '', 'Operating System Command', ''],
  ['158', 'CP-1252', 'ž', 'Small Z Caron', ''],
  ['159', 'CP-1252', 'Ÿ', 'Capital Y Diaresis', ''],
  ['160', 'CP-1252', ' ', 'No Break Space', ''],
  ['161', 'CP-1252', '¡', 'Inverted Exclamation', ''],
  ['162', 'CP-1252', '¢', 'Cent', ''],
  ['163', 'CP-1252', '£', 'Pound', ''],
  ['164', 'CP-1252', '¤', 'Currency', ''],
  ['165', 'CP-1252', '¥', 'Yen', ''],
  ['166', 'CP-1252', '¦', 'Broken Bar', ''],
  ['167', 'CP-1252', '§', 'Section', ''],
  ['168', 'CP-1252', '¨', 'Diaresis', ''],
  ['169', 'CP-1252', '©', 'Copyright', ''],
  ['170', 'CP-1252', 'ª', 'Feminine Ordinal', ''],
  ['171', 'CP-1252', '«', 'Double Left Guillement', ''],
  ['172', 'CP-1252', '¬', 'Not', ''],
  ['173', 'CP-1252', '­', 'Soft Hyphen', ''],
  ['174', 'CP-1252', '®', 'Registered', ''],
  ['175', 'CP-1252', '¯', 'Macron', ''],
  ['176', 'CP-1252', '°', 'Degree', ''],
  ['177', 'CP-1252', '±', 'Plus Minus', ''],
  ['178', 'CP-1252', '²', 'Superscript Two', ''],
  ['179', 'CP-1252', '³', 'Superscript Three', ''],
  ['180', 'CP-1252', '´', 'Acute', ''],
  ['181', 'CP-1252', 'µ', 'Micro', ''],
  ['182', 'CP-1252', '¶', 'Pilcrow', ''],
  ['183', 'CP-1252', '·', 'Middle Dot', ''],
  ['184', 'CP-1252', '¸', 'Cedilla', ''],
  ['185', 'CP-1252', '¹', 'Superscript One', ''],
  ['186', 'CP-1252', 'º', 'Masculine Ordinal', ''],
  ['187', 'CP-1252', '»', 'Double Right Guillement', ''],
  ['188', 'CP-1252', '¼', 'One Quarter Fraction', ''],
  ['189', 'CP-1252', '½', 'One Half Fraction', ''],
  ['190', 'CP-1252', '¾', 'Three Quarters Fraction', ''],
  ['191', 'CP-1252', '¿', 'Inverted Question', ''],
  ['192', 'CP-1252', 'À', 'Captial A Grave', ''],
  ['193', 'CP-1252', 'Á', '', ''],
  ['194', 'CP-1252', 'Â', '', ''],
  ['195', 'CP-1252', 'Ã', '', ''],
  ['196', 'CP-1252', 'Ä', '', ''],
  ['197', 'CP-1252', 'Å', '', ''],
  ['198', 'CP-1252', 'Æ', '', ''],
  ['199', 'CP-1252', 'Ç', '', ''],
  ['200', 'CP-1252', 'È', '', ''],
  ['201', 'CP-1252', 'É', '', ''],
  ['202', 'CP-1252', 'Ê', '', ''],
  ['203', 'CP-1252', 'Ë', '', ''],
  ['204', 'CP-1252', 'Ì', '', ''],
  ['205', 'CP-1252', 'Í', '', ''],
  ['206', 'CP-1252', 'Î', '', ''],
  ['207', 'CP-1252', 'Ï', '', ''],
  ['208', 'CP-1252', 'Ð', '', ''],
  ['209', 'CP-1252', 'Ñ', '', ''],
  ['210', 'CP-1252', 'Ò', '', ''],
  ['211', 'CP-1252', 'Ó', '', ''],
  ['212', 'CP-1252', 'Ô', '', ''],
  ['213', 'CP-1252', 'Õ', '', ''],
  ['214', 'CP-1252', 'Ö', '', ''],
  ['215', 'CP-1252', '×', '', ''],
  ['216', 'CP-1252', 'Ø', '', ''],
  ['217', 'CP-1252', 'Ù', '', ''],
  ['218', 'CP-1252', 'Ú', '', ''],
  ['219', 'CP-1252', 'Û', '', ''],
  ['220', 'CP-1252', 'Ü', '', ''],
  ['221', 'CP-1252', 'Ý', '', ''],
  ['222', 'CP-1252', 'Þ', '', ''],
  ['223', 'CP-1252', 'ß', '', ''],
  ['224', 'CP-1252', 'à', '', ''],
  ['225', 'CP-1252', 'á', '', ''],
  ['226', 'CP-1252', 'â', '', ''],
  ['227', 'CP-1252', 'ã', '', ''],
  ['228', 'CP-1252', 'ä', '', ''],
  ['229', 'CP-1252', 'å', '', ''],
  ['230', 'CP-1252', 'æ', '', ''],
  ['231', 'CP-1252', 'ç', '', ''],
  ['232', 'CP-1252', 'è', '', ''],
  ['233', 'CP-1252', 'é', '', ''],
  ['234', 'CP-1252', 'ê', '', ''],
  ['235', 'CP-1252', 'ë', '', ''],
  ['236', 'CP-1252', 'ì', '', ''],
  ['237', 'CP-1252', 'í', '', ''],
  ['238', 'CP-1252', 'î', '', ''],
  ['239', 'CP-1252', 'ï', '', ''],
  ['240', 'CP-1252', 'ð', '', ''],
  ['241', 'CP-1252', 'ñ', '', ''],
  ['242', 'CP-1252', 'ò', '', ''],
  ['243', 'CP-1252', 'ó', '', ''],
  ['244', 'CP-1252', 'ô', '', ''],
  ['245', 'CP-1252', 'õ', '', ''],
  ['246', 'CP-1252', 'ö', '', ''],
  ['247', 'CP-1252', '÷', '', ''],
  ['248', 'CP-1252', 'ø', '', ''],
  ['249', 'CP-1252', 'ù', '', ''],
  ['250', 'CP-1252', 'ú', '', ''],
  ['251', 'CP-1252', 'û', '', ''],
  ['252', 'CP-1252', 'ü', '', ''],
  ['253', 'CP-1252', 'ý', '', ''],
  ['254', 'CP-1252', 'þ', '', ''],
  ['255', 'CP-1252', 'ÿ', 'Small y Diaeresis', ''],
  ['256', 'Raw Scancode', 'KSC_00', 'No Key Pressed', ''],
  ['257', 'Raw Scancode', 'KSC_01', 'Keyboard Error Roll Over', ''],
  ['258', 'Raw Scancode', 'KSC_02', 'Keyboard POST Fail', ''],
  ['259', 'Raw Scancode', 'KSC_03', 'Keyboard Error Undefined', ''],
  [
    '260',
    'Raw Scancode',
    'KEY_A',
    'Keyboard a and A (US English)',
    'Non US English keyboard users may prefer these Raw Scancodes',
  ],
  ['261', 'Raw Scancode', 'KEY_B', 'Keyboard b and B (US English)', ''],
  ['262', 'Raw Scancode', 'KEY_C', 'Keyboard c and C (US English)', ''],
  ['263', 'Raw Scancode', 'KEY_D', 'Keyboard d and D (US English)', ''],
  ['264', 'Raw Scancode', 'KEY_E', 'Keyboard e and E (US English)', ''],
  ['265', 'Raw Scancode', 'KEY_F', 'Keyboard f and F (US English)', ''],
  ['266', 'Raw Scancode', 'KEY_G', 'Keyboard g and G (US English)', ''],
  ['267', 'Raw Scancode', 'KEY_H', 'Keyboard h and H (US English)', ''],
  ['268', 'Raw Scancode', 'KEY_I', 'Keyboard i and I (US English)', ''],
  ['269', 'Raw Scancode', 'KEY_J', 'Keyboard j and J (US English)', ''],
  ['270', 'Raw Scancode', 'KEY_K', 'Keyboard k and K (US English)', ''],
  ['271', 'Raw Scancode', 'KEY_L', 'Keyboard l and L (US English)', ''],
  ['272', 'Raw Scancode', 'KEY_M', 'Keyboard m and M (US English)', ''],
  ['273', 'Raw Scancode', 'KEY_N', 'Keyboard n and N (US English)', ''],
  ['274', 'Raw Scancode', 'KEY_O', 'Keyboard o and O (US English)', ''],
  ['275', 'Raw Scancode', 'KEY_P', 'Keyboard p and P (US English)', ''],
  ['276', 'Raw Scancode', 'KEY_Q', 'Keyboard q and Q (US English)', ''],
  ['277', 'Raw Scancode', 'KEY_R', 'Keyboard r and R (US English)', ''],
  ['278', 'Raw Scancode', 'KEY_S', 'Keyboard s and S (US English)', ''],
  ['279', 'Raw Scancode', 'KEY_T', 'Keyboard t and T (US English)', ''],
  ['280', 'Raw Scancode', 'KEY_U', 'Keyboard u and U (US English)', ''],
  ['281', 'Raw Scancode', 'KEY_V', 'Keyboard v and V (US English)', ''],
  ['282', 'Raw Scancode', 'KEY_W', 'Keyboard w and W (US English)', ''],
  ['283', 'Raw Scancode', 'KEY_X', 'Keyboard x and X (US English)', ''],
  ['284', 'Raw Scancode', 'KEY_Y', 'Keyboard y and Y (US English)', ''],
  ['285', 'Raw Scancode', 'KEY_Z', 'Keyboard z and Z (US English)', ''],
  ['286', 'Raw Scancode', 'KEY_1', 'Keyboard 1 and ! (US English)', ''],
  ['287', 'Raw Scancode', 'KEY_2', 'Keyboard 2 and @ (US English)', ''],
  ['288', 'Raw Scancode', 'KEY_3', 'Keyboard 3 and # (US English)', ''],
  ['289', 'Raw Scancode', 'KEY_4', 'Keyboard 4 and $ (US English)', ''],
  ['290', 'Raw Scancode', 'KEY_5', 'Keyboard 5 and % (US English)', ''],
  ['291', 'Raw Scancode', 'KEY_6', 'Keyboard 6 and ^ (US English)', ''],
  ['292', 'Raw Scancode', 'KEY_7', 'Keyboard 7 and & (US English)', ''],
  ['293', 'Raw Scancode', 'KEY_8', 'Keyboard 8 and * (US English)', ''],
  ['294', 'Raw Scancode', 'KEY_9', 'Keyboard 9 and ( (US English)', ''],
  ['295', 'Raw Scancode', 'KEY_0', 'Keyboard 0 and ) (US English)', ''],
  ['296', 'Raw Scancode', 'ENTER', 'Keyboard Return (US English)', ''],
  ['297', 'Raw Scancode', 'ESC', 'Keyboard Escape (US English)', ''],
  ['298', 'Raw Scancode', 'BKSP', 'Keyboard Backspace (US English)', ''],
  ['299', 'Raw Scancode', 'TAB', 'Keyboard Tab (US English)', ''],
  [
    '300',
    'Raw Scancode',
    'KSC_2C',
    'Keyboard Space (US English)',
    'The ASCII space is preferred over this raw scancode for the spacebar',
  ],
  ['301', 'Raw Scancode', 'KSC_2D', 'Keyboard - and _ (US English)', ''],
  ['302', 'Raw Scancode', 'KSC_2E', 'Keyboard = and + (US English)', ''],
  ['303', 'Raw Scancode', 'KSC_2F', 'Keyboard [ and { (US English)', ''],
  ['304', 'Raw Scancode', 'KSC_30', 'Keyboard ] and } (US English)', ''],
  ['305', 'Raw Scancode', 'KSC_31', 'Keyboard \\ and | (US English)', ''],
  ['306', 'Raw Scancode', 'KSC_32', 'Keyboard Non-US # and ~ (US English)', ''],
  ['307', 'Raw Scancode', 'KSC_33', 'Keyboard ; and : (US English)', ''],
  ['308', 'Raw Scancode', 'KSC_34', 'Keyboard \' and " (US English)', ''],
  ['309', 'Raw Scancode', 'KSC_35', 'Keyboard ` and ~ (US English)', ''],
  ['310', 'Raw Scancode', 'KSC_36', 'Keyboard , and < (US English)', ''],
  ['311', 'Raw Scancode', 'KSC_37', 'Keyboard . and > (US English)', ''],
  ['312', 'Raw Scancode', 'KSC_38', 'Keyboard / and ? (US English)', ''],
  ['313', 'Raw Scancode', 'CAPSLOCK', 'Keyboard Caps Lock', ''],
  ['314', 'Raw Scancode', 'F1', 'Keyboard F1', ''],
  ['315', 'Raw Scancode', 'F2', 'Keyboard F2', ''],
  ['316', 'Raw Scancode', 'F3', 'Keyboard F3', ''],
  ['317', 'Raw Scancode', 'F4', 'Keyboard F4', ''],
  ['318', 'Raw Scancode', 'F5', 'Keyboard F5', ''],
  ['319', 'Raw Scancode', 'F6', 'Keyboard F6', ''],
  ['320', 'Raw Scancode', 'F7', 'Keyboard F7', ''],
  ['321', 'Raw Scancode', 'F8', 'Keyboard F8', ''],
  ['322', 'Raw Scancode', 'F9', 'Keyboard F9', ''],
  ['323', 'Raw Scancode', 'F10', 'Keyboard F10', ''],
  ['324', 'Raw Scancode', 'F11', 'Keyboard F11', ''],
  ['325', 'Raw Scancode', 'F12', 'Keyboard F12', ''],
  ['326', 'Raw Scancode', 'PRTSCN', 'Keyboard Print Screen', ''],
  ['327', 'Raw Scancode', 'SCRLK', 'Keyboard Scroll Lock', ''],
  ['328', 'Raw Scancode', 'PAUSE', 'Keyboard Pause', ''],
  ['329', 'Raw Scancode', 'INSERT', 'Keyboard Insert', ''],
  ['330', 'Raw Scancode', 'HOME', 'Keyboard Home', ''],
  ['331', 'Raw Scancode', 'PGUP', 'Keyboard Page Up', ''],
  ['332', 'Raw Scancode', 'DELETE', 'Keyboard Delete Forward', ''],
  ['333', 'Raw Scancode', 'END', 'Keyboard End', ''],
  ['334', 'Raw Scancode', 'PGDN', 'Keyboard Page Down', ''],
  ['335', 'Raw Scancode', 'ARROW_RT', 'Keyboard Right Arrow', ''],
  ['336', 'Raw Scancode', 'ARROW_LF', 'Keyboard Left Arrow', ''],
  ['337', 'Raw Scancode', 'ARROW_DN', 'Keyboard Down Arrow', ''],
  ['338', 'Raw Scancode', 'ARROW_UP', 'Keyboard Up Arrow', ''],
  ['339', 'Raw Scancode', 'NUMLOCK', 'Keyboard Num Lock and Clear', ''],
  ['340', 'Raw Scancode', 'KP_SLASH', 'Keypad /', ''],
  ['341', 'Raw Scancode', 'KP_ASTER', 'Keypad *', ''],
  ['342', 'Raw Scancode', 'KP_MINUS', 'Keypad -', ''],
  ['343', 'Raw Scancode', 'KP_PLUS', 'Keypad +', ''],
  ['344', 'Raw Scancode', 'KP_ENTER', 'Keypad Enter', ''],
  ['345', 'Raw Scancode', 'KP_1', 'Keypad 1 and End', ''],
  ['346', 'Raw Scancode', 'KP_2', 'Keypad 2 and Down Arrow', ''],
  ['347', 'Raw Scancode', 'KP_3', 'Keypad 3 and Page Down', ''],
  ['348', 'Raw Scancode', 'KP_4', 'Keypad 4 and Left Arrow', ''],
  ['349', 'Raw Scancode', 'KP_5', 'Keypad 5', ''],
  ['350', 'Raw Scancode', 'KP_6', 'Keypad 6 and Rigth Arrow', ''],
  ['351', 'Raw Scancode', 'KP_7', 'Keypad 7 and Home', ''],
  ['352', 'Raw Scancode', 'KP_8', 'Keypad 8 and Up Arrow', ''],
  ['353', 'Raw Scancode', 'KP_9', 'Keypad 9 and Page Up', ''],
  ['354', 'Raw Scancode', 'KP_0', 'Keypad 0 and Insert', ''],
  ['355', 'Raw Scancode', 'KP_DOT', 'Keypad . and Delete', ''],
  [
    '356',
    'Raw Scancode',
    'KSC_64',
    'Keyboard Non-US \\ and | (US English)',
    '',
  ],
  [
    '357',
    'Raw Scancode',
    'COMPOSE',
    'Keyboard Application',
    'Officially supported by Win, Unix, and Boot',
  ],
  [
    '358',
    'Raw Scancode',
    'POWER',
    'Keyboard Power',
    'Only officially supported by Mac and Unix',
  ],
  [
    '359',
    'Raw Scancode',
    'KP_EQUAL',
    'Keypad =',
    'Only officially supported by Mac',
  ],
  [
    '360',
    'Raw Scancode',
    'F13',
    'Keyboard F13',
    'Only officially supported by Mac',
  ],
  [
    '361',
    'Raw Scancode',
    'F14',
    'Keyboard F14',
    'Only officially supported by Mac',
  ],
  [
    '362',
    'Raw Scancode',
    'F15',
    'Keyboard F15',
    'Only officially supported by Mac',
  ],
  [
    '363',
    'Raw Scancode',
    'F16',
    'Keyboard F16',
    'Only officially supported by Mac',
  ],
  [
    '364',
    'Raw Scancode',
    'F17',
    'Keyboard F17',
    'Not required to be supported by any OS',
  ],
  [
    '365',
    'Raw Scancode',
    'F18',
    'Keyboard F18',
    'Not required to be supported by any OS',
  ],
  [
    '366',
    'Raw Scancode',
    'F19',
    'Keyboard F19',
    'Not required to be supported by any OS',
  ],
  [
    '367',
    'Raw Scancode',
    'F20',
    'Keyboard F20',
    'Not required to be supported by any OS',
  ],
  [
    '368',
    'Raw Scancode',
    'F21',
    'Keyboard F21',
    'Not required to be supported by any OS',
  ],
  [
    '369',
    'Raw Scancode',
    'F22',
    'Keyboard F22',
    'Not required to be supported by any OS',
  ],
  [
    '370',
    'Raw Scancode',
    'F23',
    'Keyboard F23',
    'Not required to be supported by any OS',
  ],
  [
    '371',
    'Raw Scancode',
    'F24',
    'Keyboard F24',
    'Not required to be supported by any OS',
  ],
  [
    '372',
    'Raw Scancode',
    'EXECUTE',
    'Keyboard Execute',
    'Only officially supported by Unix',
  ],
  [
    '373',
    'Raw Scancode',
    'HELP',
    'Keyboard Help',
    'Only officially supported by Unix',
  ],
  [
    '374',
    'Raw Scancode',
    'MENU',
    'Keyboard Menu',
    'Only officially supported by Unix',
  ],
  [
    '375',
    'Raw Scancode',
    'SELECT',
    'Keyboard Select',
    'Only officially supported by Unix',
  ],
  [
    '376',
    'Raw Scancode',
    'STOP',
    'Keyboard Stop',
    'Only officially supported by Unix',
  ],
  [
    '377',
    'Raw Scancode',
    'AGAIN',
    'Keyboard Again',
    'Only officially supported by Unix',
  ],
  [
    '378',
    'Raw Scancode',
    'UNDO',
    'Keyboard Undo',
    'Only officially supported by Unix',
  ],
  [
    '379',
    'Raw Scancode',
    'CUT',
    'Keyboard Cut',
    'Only officially supported by Unix',
  ],
  [
    '380',
    'Raw Scancode',
    'COPY',
    'Keyboard Copy',
    'Only officially supported by Unix',
  ],
  [
    '381',
    'Raw Scancode',
    'PASTE',
    'Keyboard Paste',
    'Only officially supported by Unix',
  ],
  [
    '382',
    'Raw Scancode',
    'FIND',
    'Keyboard Find',
    'Only officially supported by Unix',
  ],
  [
    '383',
    'Raw Scancode',
    'MUTE',
    'Keyboard Mute',
    'Only officially supported by Unix',
  ],
  [
    '384',
    'Raw Scancode',
    'VOL_UP',
    'Keyboard Volume Up',
    'Only officially supported by Unix',
  ],
  [
    '385',
    'Raw Scancode',
    'VOL_DN',
    'Keyboard Volume Down',
    'Only officially supported by Unix',
  ],
  [
    '386',
    'Raw Scancode',
    'KSC_82',
    'Keyboard Locking Caps Lock',
    'Only officially supported by Unix',
  ],
  [
    '387',
    'Raw Scancode',
    'KSC_83',
    'Keyboard Locking Num Lock',
    'Only officially supported by Unix',
  ],
  [
    '388',
    'Raw Scancode',
    'KSC_84',
    'Keyboard Locking Scroll Lock',
    'Only officially supported by Unix',
  ],
  [
    '389',
    'Raw Scancode',
    'KP_COMMA',
    'Keypad Comma',
    'Not required to be supported by any OS',
  ],
  [
    '390',
    'Raw Scancode',
    'KSC_86',
    'Keypad Equals Sign',
    'Not required to be supported by any OS',
  ],
  [
    '391',
    'Raw Scancode',
    'INTL1',
    'Keyboard International1',
    'Not required to be supported by any OS',
  ],
  [
    '392',
    'Raw Scancode',
    'INTL2',
    'Keyboard International2',
    'Not required to be supported by any OS',
  ],
  [
    '393',
    'Raw Scancode',
    'INTL3',
    'Keyboard International3',
    'Not required to be supported by any OS',
  ],
  [
    '394',
    'Raw Scancode',
    'INTL4',
    'Keyboard International4',
    'Not required to be supported by any OS',
  ],
  [
    '395',
    'Raw Scancode',
    'INTL5',
    'Keyboard International5',
    'Not required to be supported by any OS',
  ],
  [
    '396',
    'Raw Scancode',
    'INTL6',
    'Keyboard International6',
    'Not required to be supported by any OS',
  ],
  [
    '397',
    'Raw Scancode',
    'INTL7',
    'Keyboard International7',
    'Not required to be supported by any OS',
  ],
  [
    '398',
    'Raw Scancode',
    'INTL8',
    'Keyboard International8',
    'Not required to be supported by any OS',
  ],
  [
    '399',
    'Raw Scancode',
    'INTL9',
    'Keyboard International9',
    'Not required to be supported by any OS',
  ],
  [
    '400',
    'Raw Scancode',
    'LANG1',
    'Keyboard LANG1',
    'Not required to be supported by any OS',
  ],
  [
    '401',
    'Raw Scancode',
    'LANG2',
    'Keyboard LANG2',
    'Not required to be supported by any OS',
  ],
  [
    '402',
    'Raw Scancode',
    'LANG3',
    'Keyboard LANG3',
    'Not required to be supported by any OS',
  ],
  [
    '403',
    'Raw Scancode',
    'LANG4',
    'Keyboard LANG4',
    'Not required to be supported by any OS',
  ],
  [
    '404',
    'Raw Scancode',
    'LANG5',
    'Keyboard LANG5',
    'Not required to be supported by any OS',
  ],
  [
    '405',
    'Raw Scancode',
    'LANG6',
    'Keyboard LANG6',
    'Not required to be supported by any OS',
  ],
  [
    '406',
    'Raw Scancode',
    'LANG7',
    'Keyboard LANG7',
    'Not required to be supported by any OS',
  ],
  [
    '407',
    'Raw Scancode',
    'LANG8',
    'Keyboard LANG8',
    'Not required to be supported by any OS',
  ],
  [
    '408',
    'Raw Scancode',
    'LANG9',
    'Keyboard LANG9',
    'Not required to be supported by any OS',
  ],
  [
    '409',
    'Raw Scancode',
    'KSC_99',
    'Keyboard Alternate Erase',
    'Not required to be supported by any OS',
  ],
  [
    '410',
    'Raw Scancode',
    'KSC_9A',
    'Keyboard SysReq/Attention',
    'Not required to be supported by any OS',
  ],
  [
    '411',
    'Raw Scancode',
    'KSC_9B',
    'Keyboard Cancel',
    'Not required to be supported by any OS',
  ],
  [
    '412',
    'Raw Scancode',
    'KSC_9C',
    'Keyboard Clear',
    'Not required to be supported by any OS',
  ],
  [
    '413',
    'Raw Scancode',
    'KSC_9D',
    'Keyboard Prior',
    'Not required to be supported by any OS',
  ],
  [
    '414',
    'Raw Scancode',
    'KSC_9E',
    'Keyboard Return',
    'Not required to be supported by any OS',
  ],
  [
    '415',
    'Raw Scancode',
    'KSC_9F',
    'Keyboard Separator',
    'Not required to be supported by any OS',
  ],
  [
    '416',
    'Raw Scancode',
    'KSC_A0',
    'Keyboard Out',
    'Not required to be supported by any OS',
  ],
  [
    '417',
    'Raw Scancode',
    'KSC_A1',
    'Keyboard Oper',
    'Not required to be supported by any OS',
  ],
  [
    '418',
    'Raw Scancode',
    'KSC_A2',
    'Keyboard Clear/Again',
    'Not required to be supported by any OS',
  ],
  [
    '419',
    'Raw Scancode',
    'KSC_A3',
    'Keyboard CrSel/Props',
    'Not required to be supported by any OS',
  ],
  [
    '420',
    'Raw Scancode',
    'KSC_A4',
    'Keyboard ExSel',
    'Not required to be supported by any OS',
  ],
  [
    '421',
    'Raw Scancode',
    'KSC_A5',
    '',
    'Not required to be supported by any OS',
  ],
  [
    '422',
    'Raw Scancode',
    'KSC_A6',
    '',
    'Not required to be supported by any OS',
  ],
  [
    '423',
    'Raw Scancode',
    'KSC_A7',
    '',
    'Not required to be supported by any OS',
  ],
  [
    '424',
    'Raw Scancode',
    'KSC_A8',
    '',
    'Not required to be supported by any OS',
  ],
  [
    '425',
    'Raw Scancode',
    'KSC_A9',
    '',
    'Not required to be supported by any OS',
  ],
  [
    '426',
    'Raw Scancode',
    'KSC_AA',
    '',
    'Not required to be supported by any OS',
  ],
  [
    '427',
    'Raw Scancode',
    'KSC_AB',
    '',
    'Not required to be supported by any OS',
  ],
  [
    '428',
    'Raw Scancode',
    'KSC_AC',
    '',
    'Not required to be supported by any OS',
  ],
  [
    '429',
    'Raw Scancode',
    'KSC_AD',
    '',
    'Not required to be supported by any OS',
  ],
  [
    '430',
    'Raw Scancode',
    'KSC_AE',
    '',
    'Not required to be supported by any OS',
  ],
  [
    '431',
    'Raw Scancode',
    'KSC_AF',
    '',
    'Not required to be supported by any OS',
  ],
  [
    '432',
    'Raw Scancode',
    'KSC_B0',
    'Keypad 00',
    'Not required to be supported by any OS',
  ],
  [
    '433',
    'Raw Scancode',
    'KSC_B1',
    'Keypad 000',
    'Not required to be supported by any OS',
  ],
  [
    '434',
    'Raw Scancode',
    'KSC_B2',
    'Thousands Separator',
    'Not required to be supported by any OS',
  ],
  [
    '435',
    'Raw Scancode',
    'KSC_B3',
    'Decimal Separator',
    'Not required to be supported by any OS',
  ],
  [
    '436',
    'Raw Scancode',
    'KSC_B4',
    'Currency Unit',
    'Not required to be supported by any OS',
  ],
  [
    '437',
    'Raw Scancode',
    'KSC_B5',
    'Currency Sub-unit',
    'Not required to be supported by any OS',
  ],
  [
    '438',
    'Raw Scancode',
    'KSC_B6',
    'Keypad (',
    'Not required to be supported by any OS',
  ],
  [
    '439',
    'Raw Scancode',
    'KSC_B7',
    'Keypad )',
    'Not required to be supported by any OS',
  ],
  [
    '440',
    'Raw Scancode',
    'KSC_B8',
    'Keypad {',
    'Not required to be supported by any OS',
  ],
  [
    '441',
    'Raw Scancode',
    'KSC_B9',
    'Keypad }',
    'Not required to be supported by any OS',
  ],
  [
    '442',
    'Raw Scancode',
    'KSC_BA',
    'Keypad Tab',
    'Not required to be supported by any OS',
  ],
  [
    '443',
    'Raw Scancode',
    'KSC_BB',
    'Keypad Backspace',
    'Not required to be supported by any OS',
  ],
  [
    '444',
    'Raw Scancode',
    'KSC_BC',
    'Keypad A',
    'Not required to be supported by any OS',
  ],
  [
    '445',
    'Raw Scancode',
    'KSC_BD',
    'Keypad B',
    'Not required to be supported by any OS',
  ],
  [
    '446',
    'Raw Scancode',
    'KSC_BE',
    'Keypad C',
    'Not required to be supported by any OS',
  ],
  [
    '447',
    'Raw Scancode',
    'KSC_BF',
    'Keypad D',
    'Not required to be supported by any OS',
  ],
  [
    '448',
    'Raw Scancode',
    'KSC_C0',
    'Keypad E',
    'Not required to be supported by any OS',
  ],
  [
    '449',
    'Raw Scancode',
    'KSC_C1',
    'Keypad F',
    'Not required to be supported by any OS',
  ],
  [
    '450',
    'Raw Scancode',
    'KSC_C2',
    'Keypad XOR',
    'Not required to be supported by any OS',
  ],
  [
    '451',
    'Raw Scancode',
    'KSC_C3',
    'Keypad ^',
    'Not required to be supported by any OS',
  ],
  [
    '452',
    'Raw Scancode',
    'KSC_C4',
    'Keypad %',
    'Not required to be supported by any OS',
  ],
  [
    '453',
    'Raw Scancode',
    'KSC_C5',
    'Keypad <',
    'Not required to be supported by any OS',
  ],
  [
    '454',
    'Raw Scancode',
    'KSC_C6',
    'Keypad >',
    'Not required to be supported by any OS',
  ],
  [
    '455',
    'Raw Scancode',
    'KSC_C7',
    'Keypad &',
    'Not required to be supported by any OS',
  ],
  [
    '456',
    'Raw Scancode',
    'KSC_C8',
    'Keypad &&',
    'Not required to be supported by any OS',
  ],
  [
    '457',
    'Raw Scancode',
    'KSC_C9',
    'Keypad |',
    'Not required to be supported by any OS',
  ],
  [
    '458',
    'Raw Scancode',
    'KSC_CA',
    'Keypad ||',
    'Not required to be supported by any OS',
  ],
  [
    '459',
    'Raw Scancode',
    'KSC_CB',
    'Keypad :',
    'Not required to be supported by any OS',
  ],
  [
    '460',
    'Raw Scancode',
    'KSC_CC',
    'Keypad #',
    'Not required to be supported by any OS',
  ],
  [
    '461',
    'Raw Scancode',
    'KSC_CD',
    'Keypad Space',
    'Not required to be supported by any OS',
  ],
  [
    '462',
    'Raw Scancode',
    'KSC_CE',
    'Keypad @',
    'Not required to be supported by any OS',
  ],
  [
    '463',
    'Raw Scancode',
    'KSC_CF',
    'Keypad !',
    'Not required to be supported by any OS',
  ],
  [
    '464',
    'Raw Scancode',
    'KSC_D0',
    'Keypad Memory Store',
    'Not required to be supported by any OS',
  ],
  [
    '465',
    'Raw Scancode',
    'KSC_D1',
    'Keypad Memory Recall',
    'Not required to be supported by any OS',
  ],
  [
    '466',
    'Raw Scancode',
    'KSC_D2',
    'Keypad Memory Clear',
    'Not required to be supported by any OS',
  ],
  [
    '467',
    'Raw Scancode',
    'KSC_D3',
    'Keypad Memory Add',
    'Not required to be supported by any OS',
  ],
  [
    '468',
    'Raw Scancode',
    'KSC_D4',
    'Keypad Memory Subtract',
    'Not required to be supported by any OS',
  ],
  [
    '469',
    'Raw Scancode',
    'KSC_D5',
    'Keypad Memory Multiply',
    'Not required to be supported by any OS',
  ],
  [
    '470',
    'Raw Scancode',
    'KSC_D6',
    'Keypad Memory Divide',
    'Not required to be supported by any OS',
  ],
  [
    '471',
    'Raw Scancode',
    'KSC_D7',
    'Keypad +/-',
    'Not required to be supported by any OS',
  ],
  [
    '472',
    'Raw Scancode',
    'KSC_D8',
    'Keypad Clear',
    'Not required to be supported by any OS',
  ],
  [
    '473',
    'Raw Scancode',
    'KSC_D9',
    'Keypad Clear Entry',
    'Not required to be supported by any OS',
  ],
  [
    '474',
    'Raw Scancode',
    'KSC_DA',
    'Keypad Binary',
    'Not required to be supported by any OS',
  ],
  [
    '475',
    'Raw Scancode',
    'KSC_DB',
    'Keypad Octal',
    'Not required to be supported by any OS',
  ],
  [
    '476',
    'Raw Scancode',
    'KSC_DC',
    'Keypad Decimal',
    'Not required to be supported by any OS',
  ],
  [
    '477',
    'Raw Scancode',
    'KSC_DD',
    'Keypad Hexadecimal',
    'Not required to be supported by any OS',
  ],
  [
    '478',
    'Raw Scancode',
    'KSC_DE',
    '',
    'Not required to be supported by any OS',
  ],
  [
    '479',
    'Raw Scancode',
    'KSC_DF',
    '',
    'Not required to be supported by any OS',
  ],
  ['480', 'Raw Scancode', 'KSC_E0', 'Keyboard Left Control', ''],
  ['481', 'Raw Scancode', 'KSC_E1', 'Keyboard Left Shift', ''],
  ['482', 'Raw Scancode', 'KSC_E2', 'Keyboard Left Alt', ''],
  ['483', 'Raw Scancode', 'KSC_E3', 'Keyboard Left GUI', ''],
  ['484', 'Raw Scancode', 'KSC_E4', 'Keyboard Right Control', ''],
  ['485', 'Raw Scancode', 'KSC_E5', 'Keyboard Right Shift', ''],
  ['486', 'Raw Scancode', 'KSC_E6', 'Keyboard Right Alt', ''],
  ['487', 'Raw Scancode', 'KSC_E7', 'Keyboard Right GUI', ''],
  [
    '488',
    'Raw Scancode',
    'KSC_E8',
    'Media Play Pause',
    'Not required to be supported by any OS. Possibly deprecated.',
  ],
  [
    '489',
    'Raw Scancode',
    'KSC_E9',
    'Media Stop CD',
    'Not required to be supported by any OS. Possibly deprecated.',
  ],
  [
    '490',
    'Raw Scancode',
    'KSC_EA',
    'Media Previous Song',
    'Not required to be supported by any OS. Possibly deprecated.',
  ],
  [
    '491',
    'Raw Scancode',
    'KSC_EB',
    'Media Next Song',
    'Not required to be supported by any OS. Possibly deprecated.',
  ],
  [
    '492',
    'Raw Scancode',
    'KSC_EC',
    'Media Eject CD',
    'Not required to be supported by any OS. Possibly deprecated.',
  ],
  [
    '493',
    'Raw Scancode',
    'KSC_ED',
    'Media Volume Up',
    'Not required to be supported by any OS. Possibly deprecated.',
  ],
  [
    '494',
    'Raw Scancode',
    'KSC_EE',
    'Media Volume Down',
    'Not required to be supported by any OS. Possibly deprecated.',
  ],
  [
    '495',
    'Raw Scancode',
    'KSC_EF',
    'Media Mute',
    'Not required to be supported by any OS. Possibly deprecated.',
  ],
  [
    '496',
    'Raw Scancode',
    'KSC_F0',
    'Media www',
    'Not required to be supported by any OS. Possibly deprecated.',
  ],
  [
    '497',
    'Raw Scancode',
    'KSC_F1',
    'Media Back',
    'Not required to be supported by any OS. Possibly deprecated.',
  ],
  [
    '498',
    'Raw Scancode',
    'KSC_F2',
    'Media Forward',
    'Not required to be supported by any OS. Possibly deprecated.',
  ],
  [
    '499',
    'Raw Scancode',
    'KSC_F3',
    'Media Stop',
    'Not required to be supported by any OS. Possibly deprecated.',
  ],
  [
    '500',
    'Raw Scancode',
    'KSC_F4',
    'Media Find',
    'Not required to be supported by any OS. Possibly deprecated.',
  ],
  [
    '501',
    'Raw Scancode',
    'KSC_F5',
    'Media Scroll Up',
    'Not required to be supported by any OS. Possibly deprecated.',
  ],
  [
    '502',
    'Raw Scancode',
    'KSC_F6',
    'Media Scroll Down',
    'Not required to be supported by any OS. Possibly deprecated.',
  ],
  [
    '503',
    'Raw Scancode',
    'KSC_F7',
    'Media Edit',
    'Not required to be supported by any OS. Possibly deprecated.',
  ],
  [
    '504',
    'Raw Scancode',
    'KSC_F8',
    'Media Sleep',
    'Not required to be supported by any OS. Possibly deprecated.',
  ],
  [
    '505',
    'Raw Scancode',
    'KSC_F9',
    'Media Coffee',
    'Not required to be supported by any OS. Possibly deprecated.',
  ],
  [
    '506',
    'Raw Scancode',
    'KSC_FA',
    'Media Refresh',
    'Not required to be supported by any OS. Possibly deprecated.',
  ],
  [
    '507',
    'Raw Scancode',
    'KSC_FB',
    'Media Calc',
    'Not required to be supported by any OS. Possibly deprecated.',
  ],
  [
    '508',
    'Raw Scancode',
    'KSC_FC',
    '',
    'Not required to be supported by any OS.',
  ],
  [
    '509',
    'Raw Scancode',
    'KSC_FD',
    '',
    'Not required to be supported by any OS.',
  ],
  [
    '510',
    'Raw Scancode',
    'KSC_FE',
    '',
    'Not required to be supported by any OS.',
  ],
  [
    '511',
    'Raw Scancode',
    'KSC_FF',
    '',
    'Not required to be supported by any OS.',
  ],
  ['512', 'Keyboard', 'LEFT_CTRL', 'Left Control Keyboard Modifier', ''],
  ['513', 'Keyboard', 'LEFT_SHIFT', 'Left Shift Keyboard Modifier', ''],
  ['514', 'Keyboard', 'LEFT_ALT', 'Left Alt Keyboard Modifier', ''],
  ['515', 'Keyboard', 'LEFT_GUI', 'Left GUI Keyboard Modifier', ''],
  ['516', 'Keyboard', 'RIGHT_CTRL', 'Right Control Keyboard Modifier', ''],
  ['517', 'Keyboard', 'RIGHT_SHIFT', 'Right Shift Keyboard Modifier', ''],
  ['518', 'Keyboard', 'RIGHT_ALT', 'Right Alt Keyboard Modifier', ''],
  ['519', 'Keyboard', 'RIGHT_GUI', 'Right GUI Keyboard Modifier', ''],
  ['520', 'Keyboard', 'RELEASE_MOD', 'Release all keyboard modifiers', ''],
  [
    '521',
    'Keyboard',
    'RELEASE_ALL',
    'Release all keys and keyboard modifiers',
    '',
  ],
  [
    '522',
    'Keyboard',
    'RELEASE_KEYS',
    'Release all keys, but not keyboard modifiers',
    '',
  ],
  ['523', '', '', '', ''],
  ['524', '', '', '', ''],
  ['525', '', '', '', ''],
  ['526', '', '', '', ''],
  ['527', '', '', '', ''],
  ['528', 'CharaChorder', 'RESTART', 'Restart Device', ''],
  ['529', '', '', '', ''],
  ['530', 'CharaChorder', 'BOOT', 'Bootloader Mode', ''],
  ['531', '', '', '', ''],
  ['532', 'CharaChorder', 'GTM', 'Toggle GTM', ''],
  ['533', '', '', '', ''],
  ['534', 'CharaChorder', 'IMPULSE', 'Toggle Impulse', ''],
  ['535', '', '', '', ''],
  ['536', 'CharaChorder', 'DUP', 'Repeat Last Note', ''],
  ['537', '', '', '', ''],
  ['538', 'CharaChorder', 'SPUR', 'Spur Toggle', ''],
  ['539', '', '', '', ''],
  ['540', 'CharaChorder', 'AMBILEFT', 'AmbiThrow (left)', ''],
  ['541', '', '', '', ''],
  ['542', 'CharaChorder', 'AMBIRIGHT', 'AmbiThrow (right)', ''],
  ['543', '', '', '', ''],
  ['544', 'CharaChorder', 'SPACERIGHT', 'Right Spacebar (eg CC Lite)', ''],
  ['545', '', '', '', ''],
  ['546', '', '', '', ''],
  ['547', '', '', '', ''],
  [
    '548',
    'CharaChorder',
    'KM_1_L',
    'Primary Keymap (left key)',
    'Included for completeness',
  ],
  [
    '549',
    'CharaChorder',
    'KM_1_R',
    'Primary Keymap (right key)',
    'Included for completeness',
  ],
  [
    '550',
    'CharaChorder',
    'KM_2_L',
    'Secondary Keymap [Num-shift] (left key)',
    '',
  ],
  [
    '551',
    'CharaChorder',
    'KM_2_R',
    'Secondary Keymap [Num-shift] (right key)',
    '',
  ],
  ['552', 'CharaChorder', 'KM_3_L', 'Tertiary Keymap (left key)', ''],
  ['553', 'CharaChorder', 'KM_3_R', 'Tertiary Keymap (right key)', ''],
  ['554', '', '', '', ''],
  ['555', '', '', '', ''],
  ['556', '', '', '', ''],
  ['557', '', '', '', ''],
  ['558', '', '', '', ''],
  ['559', '', '', '', ''],
  ['560', 'Mouse', 'MS_CLICK_BWD', 'Mouse Backward Button Press/Release', ''],
  ['561', 'Mouse', 'MS_CLICK_FWD', 'Mouse Forward Button Press/Release', ''],
  ['562', 'Mouse', 'MS_CLICK_LF', 'Mouse Left Button Press/Release', ''],
  ['563', 'Mouse', 'MS_CLICK_RT', 'Mouse Right Button Press/Release', ''],
  ['564', 'Mouse', 'MS_CLICK_MD', 'Mouse Middle Button Press/Release', ''],
  ['565', 'Mouse', 'MS_MOVE_RT', 'Mouse Move Right', ''],
  ['566', 'Mouse', 'MS_MOVE_LF', 'Mouse Move Left', ''],
  ['567', 'Mouse', 'MS_MOVE_DN', 'Mouse Move Down', ''],
  ['568', 'Mouse', 'MS_MOVE_UP', 'Mouse Move Up', ''],
  ['569', 'Mouse', 'MS_SCRL_RT', 'Mouse Scroll Coast Right', ''],
  ['570', 'Mouse', 'MS_SCRL_LF', 'Mouse Scroll Coast Left', ''],
  ['571', 'Mouse', 'MS_SCRL_DN', 'Mouse Scroll Coast Down', ''],
  ['572', 'Mouse', 'MS_SCRL_UP', 'Mouse Scroll Coast Up', ''],
  ['573', '', '', '', ''],
  ['574', '', '', '', ''],
  ['575', '', '', '', ''],
  ['576', '', '', '', ''],
  ['577', '', '', '', ''],
  ['578', '', '', '', ''],
  ['579', '', '', '', ''],
  ['580', '', '', '', ''],
  ['581', '', '', '', ''],
  ['582', '', '', '', ''],
  ['583', '', '', '', ''],
  ['584', '', '', '', ''],
  ['585', '', '', '', ''],
  ['586', '', '', '', ''],
  ['587', '', '', '', ''],
  ['588', '', '', '', ''],
  ['589', '', '', '', ''],
  ['590', '', '', '', ''],
  ['591', '', '', '', ''],
  ['592', '', '', '', ''],
  ['593', '', '', '', ''],
  ['594', '', '', '', ''],
  ['595', '', '', '', ''],
  ['596', '', '', '', ''],
  ['597', '', '', '', ''],
  ['598', '', '', '', ''],
  ['599', '', '', '', ''],
  [
    '600',
    'CharaChorder One',
    'LH_THUMB_3_3D',
    'Left Hand Thumb 3 Center Switch; No action',
    'No Action; Used for chords with unassigned 3D presses on the CC1',
  ],
  ['601', 'CharaChorder One', 'LH_THUMB_2_3D', '', ''],
  ['602', 'CharaChorder One', 'LH_THUMB_1_3D', '', ''],
  ['603', 'CharaChorder One', 'LH_INDEX_3D', '', ''],
  ['604', 'CharaChorder One', 'LH_MID_1_3D', '', ''],
  ['605', 'CharaChorder One', 'LH_RING_1_3D', '', ''],
  ['606', 'CharaChorder One', 'LH_PINKY_3D', '', ''],
  ['607', 'CharaChorder One', 'LH_MID_2_3D', '', ''],
  ['608', 'CharaChorder One', 'LH_RING_2_3D', '', ''],
  ['609', 'CharaChorder One', 'RH_THUMB_3_3D', '', ''],
  ['610', 'CharaChorder One', 'RH_THUMB_2_3D', '', ''],
  ['611', 'CharaChorder One', 'RH_THUMB_1_3D', '', ''],
  ['612', 'CharaChorder One', 'RH_INDEX_3D', '', ''],
  ['613', 'CharaChorder One', 'RH_MID_1_3D', '', ''],
  ['614', 'CharaChorder One', 'RH_RING_1_3D', '', ''],
  ['615', 'CharaChorder One', 'RH_PINKY_3D', '', ''],
  ['616', 'CharaChorder One', 'RH_MID_2_3D', '', ''],
  ['617', 'CharaChorder One', 'RH_RING_2_3D', '', ''],
  ['618', '', '', '', ''],
  ['619', '', '', '', ''],
  ['620', '', '', '', ''],
  ['621', '', '', '', ''],
  ['622', '', '', '', ''],
  ['623', '', '', '', ''],
  ['624', '', '', '', ''],
  ['625', '', '', '', ''],
  ['626', '', '', '', ''],
  ['627', '', '', '', ''],
  ['628', '', '', '', ''],
  ['629', '', '', '', ''],
  ['630', '', '', '', ''],
  ['631', '', '', '', ''],
  ['632', '', '', '', ''],
  ['633', '', '', '', ''],
  ['634', '', '', '', ''],
  ['635', '', '', '', ''],
  ['636', '', '', '', ''],
  ['637', '', '', '', ''],
  ['638', '', '', '', ''],
  ['639', '', '', '', ''],
  ['640', '', '', '', ''],
  ['641', '', '', '', ''],
  ['642', '', '', '', ''],
  ['643', '', '', '', ''],
  ['644', '', '', '', ''],
  ['645', '', '', '', ''],
  ['646', '', '', '', ''],
  ['647', '', '', '', ''],
  ['648', '', '', '', ''],
  ['649', '', '', '', ''],
  ['650', '', '', '', ''],
  ['651', '', '', '', ''],
  ['652', '', '', '', ''],
  ['653', '', '', '', ''],
  ['654', '', '', '', ''],
  ['655', '', '', '', ''],
  ['656', '', '', '', ''],
  ['657', '', '', '', ''],
  ['658', '', '', '', ''],
  ['659', '', '', '', ''],
  ['660', '', '', '', ''],
  ['661', '', '', '', ''],
  ['662', '', '', '', ''],
  ['663', '', '', '', ''],
  ['664', '', '', '', ''],
  ['665', '', '', '', ''],
  ['666', '', '', '', ''],
  ['667', '', '', '', ''],
  ['668', '', '', '', ''],
  ['669', '', '', '', ''],
  ['670', '', '', '', ''],
  ['671', '', '', '', ''],
  ['672', '', '', '', ''],
  ['673', '', '', '', ''],
  ['674', '', '', '', ''],
  ['675', '', '', '', ''],
  ['676', '', '', '', ''],
  ['677', '', '', '', ''],
  ['678', '', '', '', ''],
  ['679', '', '', '', ''],
  ['680', '', '', '', ''],
  ['681', '', '', '', ''],
  ['682', '', '', '', ''],
  ['683', '', '', '', ''],
  ['684', '', '', '', ''],
  ['685', '', '', '', ''],
  ['686', '', '', '', ''],
  ['687', '', '', '', ''],
  ['688', '', '', '', ''],
  ['689', '', '', '', ''],
  ['690', '', '', '', ''],
  ['691', '', '', '', ''],
  ['692', '', '', '', ''],
  ['693', '', '', '', ''],
  ['694', '', '', '', ''],
  ['695', '', '', '', ''],
  ['696', '', '', '', ''],
  ['697', '', '', '', ''],
  ['698', '', '', '', ''],
  ['699', '', '', '', ''],
  ['700', '', '', '', ''],
  ['701', '', '', '', ''],
  ['702', '', '', '', ''],
  ['703', '', '', '', ''],
  ['704', '', '', '', ''],
  ['705', '', '', '', ''],
  ['706', '', '', '', ''],
  ['707', '', '', '', ''],
  ['708', '', '', '', ''],
  ['709', '', '', '', ''],
  ['710', '', '', '', ''],
  ['711', '', '', '', ''],
  ['712', '', '', '', ''],
  ['713', '', '', '', ''],
  ['714', '', '', '', ''],
  ['715', '', '', '', ''],
  ['716', '', '', '', ''],
  ['717', '', '', '', ''],
  ['718', '', '', '', ''],
  ['719', '', '', '', ''],
  ['720', '', '', '', ''],
  ['721', '', '', '', ''],
  ['722', '', '', '', ''],
  ['723', '', '', '', ''],
  ['724', '', '', '', ''],
  ['725', '', '', '', ''],
  ['726', '', '', '', ''],
  ['727', '', '', '', ''],
  ['728', '', '', '', ''],
  ['729', '', '', '', ''],
  ['730', '', '', '', ''],
  ['731', '', '', '', ''],
  ['732', '', '', '', ''],
  ['733', '', '', '', ''],
  ['734', '', '', '', ''],
  ['735', '', '', '', ''],
  ['736', '', '', '', ''],
  ['737', '', '', '', ''],
  ['738', '', '', '', ''],
  ['739', '', '', '', ''],
  ['740', '', '', '', ''],
  ['741', '', '', '', ''],
  ['742', '', '', '', ''],
  ['743', '', '', '', ''],
  ['744', '', '', '', ''],
  ['745', '', '', '', ''],
  ['746', '', '', '', ''],
  ['747', '', '', '', ''],
  ['748', '', '', '', ''],
  ['749', '', '', '', ''],
  ['750', '', '', '', ''],
  ['751', '', '', '', ''],
  ['752', '', '', '', ''],
  ['753', '', '', '', ''],
  ['754', '', '', '', ''],
  ['755', '', '', '', ''],
  ['756', '', '', '', ''],
  ['757', '', '', '', ''],
  ['758', '', '', '', ''],
  ['759', '', '', '', ''],
  ['760', '', '', '', ''],
  ['761', '', '', '', ''],
  ['762', '', '', '', ''],
  ['763', '', '', '', ''],
  ['764', '', '', '', ''],
  ['765', '', '', '', ''],
  ['766', '', '', '', ''],
  ['767', '', '', '', ''],
  ['768', '', '', '', ''],
  ['769', '', '', '', ''],
  ['770', '', '', '', ''],
  ['771', '', '', '', ''],
  ['772', '', '', '', ''],
  ['773', '', '', '', ''],
  ['774', '', '', '', ''],
  ['775', '', '', '', ''],
  ['776', '', '', '', ''],
  ['777', '', '', '', ''],
  ['778', '', '', '', ''],
  ['779', '', '', '', ''],
  ['780', '', '', '', ''],
  ['781', '', '', '', ''],
  ['782', '', '', '', ''],
  ['783', '', '', '', ''],
  ['784', '', '', '', ''],
  ['785', '', '', '', ''],
  ['786', '', '', '', ''],
  ['787', '', '', '', ''],
  ['788', '', '', '', ''],
  ['789', '', '', '', ''],
  ['790', '', '', '', ''],
  ['791', '', '', '', ''],
  ['792', '', '', '', ''],
  ['793', '', '', '', ''],
  ['794', '', '', '', ''],
  ['795', '', '', '', ''],
  ['796', '', '', '', ''],
  ['797', '', '', '', ''],
  ['798', '', '', '', ''],
  ['799', '', '', '', ''],
  ['800', '', '', '', ''],
  ['801', '', '', '', ''],
  ['802', '', '', '', ''],
  ['803', '', '', '', ''],
  ['804', '', '', '', ''],
  ['805', '', '', '', ''],
  ['806', '', '', '', ''],
  ['807', '', '', '', ''],
  ['808', '', '', '', ''],
  ['809', '', '', '', ''],
  ['810', '', '', '', ''],
  ['811', '', '', '', ''],
  ['812', '', '', '', ''],
  ['813', '', '', '', ''],
  ['814', '', '', '', ''],
  ['815', '', '', '', ''],
  ['816', '', '', '', ''],
  ['817', '', '', '', ''],
  ['818', '', '', '', ''],
  ['819', '', '', '', ''],
  ['820', '', '', '', ''],
  ['821', '', '', '', ''],
  ['822', '', '', '', ''],
  ['823', '', '', '', ''],
  ['824', '', '', '', ''],
  ['825', '', '', '', ''],
  ['826', '', '', '', ''],
  ['827', '', '', '', ''],
  ['828', '', '', '', ''],
  ['829', '', '', '', ''],
  ['830', '', '', '', ''],
  ['831', '', '', '', ''],
  ['832', '', '', '', ''],
  ['833', '', '', '', ''],
  ['834', '', '', '', ''],
  ['835', '', '', '', ''],
  ['836', '', '', '', ''],
  ['837', '', '', '', ''],
  ['838', '', '', '', ''],
  ['839', '', '', '', ''],
  ['840', '', '', '', ''],
  ['841', '', '', '', ''],
  ['842', '', '', '', ''],
  ['843', '', '', '', ''],
  ['844', '', '', '', ''],
  ['845', '', '', '', ''],
  ['846', '', '', '', ''],
  ['847', '', '', '', ''],
  ['848', '', '', '', ''],
  ['849', '', '', '', ''],
  ['850', '', '', '', ''],
  ['851', '', '', '', ''],
  ['852', '', '', '', ''],
  ['853', '', '', '', ''],
  ['854', '', '', '', ''],
  ['855', '', '', '', ''],
  ['856', '', '', '', ''],
  ['857', '', '', '', ''],
  ['858', '', '', '', ''],
  ['859', '', '', '', ''],
  ['860', '', '', '', ''],
  ['861', '', '', '', ''],
  ['862', '', '', '', ''],
  ['863', '', '', '', ''],
  ['864', '', '', '', ''],
  ['865', '', '', '', ''],
  ['866', '', '', '', ''],
  ['867', '', '', '', ''],
  ['868', '', '', '', ''],
  ['869', '', '', '', ''],
  ['870', '', '', '', ''],
  ['871', '', '', '', ''],
  ['872', '', '', '', ''],
  ['873', '', '', '', ''],
  ['874', '', '', '', ''],
  ['875', '', '', '', ''],
  ['876', '', '', '', ''],
  ['877', '', '', '', ''],
  ['878', '', '', '', ''],
  ['879', '', '', '', ''],
  ['880', '', '', '', ''],
  ['881', '', '', '', ''],
  ['882', '', '', '', ''],
  ['883', '', '', '', ''],
  ['884', '', '', '', ''],
  ['885', '', '', '', ''],
  ['886', '', '', '', ''],
  ['887', '', '', '', ''],
  ['888', '', '', '', ''],
  ['889', '', '', '', ''],
  ['890', '', '', '', ''],
  ['891', '', '', '', ''],
  ['892', '', '', '', ''],
  ['893', '', '', '', ''],
  ['894', '', '', '', ''],
  ['895', '', '', '', ''],
  ['896', '', '', '', ''],
  ['897', '', '', '', ''],
  ['898', '', '', '', ''],
  ['899', '', '', '', ''],
  ['900', '', '', '', ''],
  ['901', '', '', '', ''],
  ['902', '', '', '', ''],
  ['903', '', '', '', ''],
  ['904', '', '', '', ''],
  ['905', '', '', '', ''],
  ['906', '', '', '', ''],
  ['907', '', '', '', ''],
  ['908', '', '', '', ''],
  ['909', '', '', '', ''],
  ['910', '', '', '', ''],
  ['911', '', '', '', ''],
  ['912', '', '', '', ''],
  ['913', '', '', '', ''],
  ['914', '', '', '', ''],
  ['915', '', '', '', ''],
  ['916', '', '', '', ''],
  ['917', '', '', '', ''],
  ['918', '', '', '', ''],
  ['919', '', '', '', ''],
  ['920', '', '', '', ''],
  ['921', '', '', '', ''],
  ['922', '', '', '', ''],
  ['923', '', '', '', ''],
  ['924', '', '', '', ''],
  ['925', '', '', '', ''],
  ['926', '', '', '', ''],
  ['927', '', '', '', ''],
  ['928', '', '', '', ''],
  ['929', '', '', '', ''],
  ['930', '', '', '', ''],
  ['931', '', '', '', ''],
  ['932', '', '', '', ''],
  ['933', '', '', '', ''],
  ['934', '', '', '', ''],
  ['935', '', '', '', ''],
  ['936', '', '', '', ''],
  ['937', '', '', '', ''],
  ['938', '', '', '', ''],
  ['939', '', '', '', ''],
  ['940', '', '', '', ''],
  ['941', '', '', '', ''],
  ['942', '', '', '', ''],
  ['943', '', '', '', ''],
  ['944', '', '', '', ''],
  ['945', '', '', '', ''],
  ['946', '', '', '', ''],
  ['947', '', '', '', ''],
  ['948', '', '', '', ''],
  ['949', '', '', '', ''],
  ['950', '', '', '', ''],
  ['951', '', '', '', ''],
  ['952', '', '', '', ''],
  ['953', '', '', '', ''],
  ['954', '', '', '', ''],
  ['955', '', '', '', ''],
  ['956', '', '', '', ''],
  ['957', '', '', '', ''],
  ['958', '', '', '', ''],
  ['959', '', '', '', ''],
  ['960', '', '', '', ''],
  ['961', '', '', '', ''],
  ['962', '', '', '', ''],
  ['963', '', '', '', ''],
  ['964', '', '', '', ''],
  ['965', '', '', '', ''],
  ['966', '', '', '', ''],
  ['967', '', '', '', ''],
  ['968', '', '', '', ''],
  ['969', '', '', '', ''],
  ['970', '', '', '', ''],
  ['971', '', '', '', ''],
  ['972', '', '', '', ''],
  ['973', '', '', '', ''],
  ['974', '', '', '', ''],
  ['975', '', '', '', ''],
  ['976', '', '', '', ''],
  ['977', '', '', '', ''],
  ['978', '', '', '', ''],
  ['979', '', '', '', ''],
  ['980', '', '', '', ''],
  ['981', '', '', '', ''],
  ['982', '', '', '', ''],
  ['983', '', '', '', ''],
  ['984', '', '', '', ''],
  ['985', '', '', '', ''],
  ['986', '', '', '', ''],
  ['987', '', '', '', ''],
  ['988', '', '', '', ''],
  ['989', '', '', '', ''],
  ['990', '', '', '', ''],
  ['991', '', '', '', ''],
  ['992', '', '', '', ''],
  ['993', '', '', '', ''],
  ['994', '', '', '', ''],
  ['995', '', '', '', ''],
  ['996', '', '', '', ''],
  ['997', '', '', '', ''],
  ['998', '', '', '', ''],
  ['999', '', '', '', ''],
  ['1000', '', '', '', ''],
  ['1001', '', '', '', ''],
  ['1002', '', '', '', ''],
  ['1003', '', '', '', ''],
  ['1004', '', '', '', ''],
  ['1005', '', '', '', ''],
  ['1006', '', '', '', ''],
  ['1007', '', '', '', ''],
  ['1008', '', '', '', ''],
  ['1009', '', '', '', ''],
  ['1010', '', '', '', ''],
  ['1011', '', '', '', ''],
  ['1012', '', '', '', ''],
  ['1013', '', '', '', ''],
  ['1014', '', '', '', ''],
  ['1015', '', '', '', ''],
  ['1016', '', '', '', ''],
  ['1017', '', '', '', ''],
  ['1018', '', '', '', ''],
  ['1019', '', '', '', ''],
  ['1020', '', '', '', ''],
  ['1021', '', '', '', ''],
  ['1022', '', '', '', ''],
  ['1023', '', '', '', ''],
];
