export type TrainingScenario =
  | 'ALPHABET'
  | 'TRIGRAM'
  | 'LEXICAL'
  | 'CHORDING'
  | 'LEXICOGRAPHIC'
  | 'SUPERSONIC'
  | 'CUSTOMTIER'
  | 'ALLCHORDS'
  | 'LEXICALSENTENCES'
  | 'LEXICALSENTENCESDUOS'
  | 'LEXICALSENTENCESTRIOS';
